pin "solid_queue_web", to: "solid_queue_web/application.js"
pin "solid_queue_web/search_controller", to: "solid_queue_web/search_controller.js"
pin "solid_queue_web/refresh_controller", to: "solid_queue_web/refresh_controller.js"
pin "solid_queue_web/selection_controller", to: "solid_queue_web/selection_controller.js"
pin "solid_queue_web/theme_controller", to: "solid_queue_web/theme_controller.js"
